# Generated by Django 5.2.4 on 2025-08-01 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Lenguajes de Programación', 'Programming Languages'), ('Framework', 'Framework'), ('Bases de Datos', 'Databases'), ('Herramientas', 'Tools'), ('Otros', 'Others')], default='Lenguajes de Programación', max_length=50, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
