version: "3.7"

services:
  db:
    image: postgres:14.3
    container_name: curriculum-vitae-postgres-db
    restart: always
    environment:
      POSTGRES_DB: curriculum_vitae-db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 5433:5432
    networks:
      - alt-network
    volumes:
      - dbdatacv:/var/lib/postgresql/data

  backend-django-curriculum_vitae:
    image: fabiocordobadev/personal:backend-django-curriculum_vitae
    container_name: backend-django-curriculum_vitae
    restart: always
    ports:
      - 8110:8000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: curriculum_vitae-db
      DATABASE_USER: db_user
      DATABASE_PASSWORD: db_password
    networks:
      - alt-network
networks:
  alt-network:


volumes:
  dbdatacv:
